### ISSUE TITLE
Crashing on 1.19.2

### ISSUE THREAD

**Issue by vivagabe** [teamfusion/finsandtails#20]
[crash-2023-02-27_22.43.04-server.txt](https://github.com/teamfusion/finsandtails/files/10847351/crash-2023-02-27_22.43.04-server.txt)

Please let me know if you need anything else!

THanks!

**Comment by mightyjaffa12** [comment]
Im also having this issue on my server

**Comment by baguchi** [comment]
sorry for bother about that. have you tried newer bugfix version?

**Comment by mightyjaffa12** [comment]
yeah the newer version fixed it for me, not had this issue since updating
